// Code generated by go:generate; DO NOT EDIT.
package testdata

import "fmt"

var AllSides = map[Side]struct{}{
	SideBuy:  {},
	SideSell: {},
}

var AllSidesSlice = []Side{
	SideBuy,
	SideSell,
}

func SideStrings(slice []Side) (out []int) {
	for _, el := range slice {
		out = append(out, fmt.Sprintf("%d", el))
	}
	return out
}

// SideKeys converts a map of Side to a slice of Side
func SideKeys(values map[Side]struct{}) (slice []Side) {
	for k := range values {
		slice = append(slice, k)
	}
	return slice
}

// ValidateSide validates a value of type Side
func ValidateSide(ch Side) bool {
	_, ok := AllSides[ch]
	return ok
}
